### PR TITLE
Data recrawl

### PR DESCRIPTION
**Pull request by glatard**
This is a recrawl of the dataset using the files made available at https://amnesia.cbrain.mcgill.ca/SIMON_data

A PR will follow with the git-annex branch.

Thanks @xlecours for all the help.

### CODE REVIEW

**Review by xlecours — CHANGES_REQUESTED** [review]
@glatard DATS.json is in the annex but should be in git.

**Comment by emmetaobrien** [comment]
That looks to be downloading fine; was it intended that the .json files in the subdirectories would be annexed ?

**Comment by glatard** [comment]
This is ready for another review:
* @xlecours DATS.json is now in Git instead of the annex
* @emmetaobrien I don't think we have a policy on putting JSON files in the annex or out. Many JSON files were part of the annex in the previous version so I let them there.
Sorry for the large number of commits, I struggled with datalad to remove files from the annex, please squash and merge!

**Comment by jbpoline** [comment]
I  `datalad install git@github.com:conpdatasets/SIMON-dataset.git`
something to setup for git-annex to `datalad get` ?

**Comment by glatard** [comment]
@jbpoline this is a PR, it's not merged to `git@github.com:conpdatasets/SIMON-dataset.git` yet. Datalad get from `git@github.com:conpdatasets/SIMON-dataset.git` is failing because the dataset is broken. This PR is supposed to fix it.

**Comment by emmetaobrien** [comment]
Using `datalad get` on files after installing from  `glatard:master` is working fine, links aren't broken and we no longer have the 10GB index file issue.

**Review by emmetaobrien — APPROVED** [review]
This looks good to go.

**Pull request merged**
